require("brunobragaw8t.options")
require("brunobragaw8t.keymaps")
require("brunobragaw8t.plugins")
require("brunobragaw8t.colorscheme")
require("brunobragaw8t.telescope")
require("brunobragaw8t.nvim-tree")
require("brunobragaw8t.lualine")
require("brunobragaw8t.bufferline")
require("brunobragaw8t.toggleterm")
require("brunobragaw8t.gitsigns")
require("brunobragaw8t.which-key")
-- require("brunobragaw8t.lsp")
-- require("brunobragaw8t.cmp")
-- require("brunobragaw8t.treesitter")
-- require("brunobragaw8t.autopairs")
-- require("brunobragaw8t.comment")
