require('brunobragaw8t.options')
require('brunobragaw8t.keymaps')
require('brunobragaw8t.plugins')
require('brunobragaw8t.colorscheme')
require('brunobragaw8t.cmp')
require('brunobragaw8t.lsp')
require('brunobragaw8t.telescope')
