vim.opt.clipboard = "unnamedplus" -- Allow Neovim to access system clipboard
vim.opt.cursorline = true         -- Highlight current line
vim.opt.number = true             -- Display line numbers
vim.opt.relativenumber = true     -- Set line numbers as relative
vim.opt.scrolloff = 999           -- Keep cursor vertically centered on screen
vim.opt.sidescrolloff = 16        -- Don't let cursor touch side of window
vim.opt.wrap = false              -- Don't wrap long lines
vim.opt.fileformats = "unix"      -- Set default end-of-line character to LF
vim.opt.shiftwidth = 2            -- Set tab width to 2 spaces
vim.opt.tabstop = 2               -- Set tab width to 2 spaces
vim.opt.expandtab = true          -- Convert tabs to spaces
vim.opt.undofile = true           -- Save undo history for closed files
vim.opt.colorcolumn = "80,120"    -- Set line-length rulers
