vim.opt.cursorline = true     -- Highlight current line
vim.opt.number = true         -- Display line numbers
vim.opt.relativenumber = true -- Set line numbers as relative
vim.opt.scrolloff = 999       -- Keep cursor vertically centered on screen
vim.opt.sidescrolloff = 999   -- Keep cursor horizontally centered on screen
vim.opt.wrap = false          -- Don't wrap long lines
vim.opt.mouse = ''            -- Disable mouse
vim.opt.fileformats = 'unix'  -- Set line ending to LF
vim.opt.shiftwidth = 2        -- Set tab width to 2 spaces
vim.opt.tabstop = 2           -- Set tab width to 2 spaces
vim.opt.expandtab = true      -- Convert tabs to spaces
